version: '3'

services:
  backend:
    image: ${ECR_REGISTRY:-registry}/${ECR_BACKEND_REPOSITORY:-backend-repo}:${RELEASE_VERSION:-dev}
    container_name: "backend"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
  frontend:
    image: ${ECR_REGISTRY:-registry}/${ECR_BACKEND_REPOSITORY:-backend-repo}:${RELEASE_VERSION:-dev}
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    environment:
      - API_URI=http://localhost:4000
      - API_URI_DOCKER=http://backend:4000
    ports:
      - "3000:3000"
    links:
      - "backend:be"